version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: loglens
      POSTGRES_PASSWORD: loglens
      POSTGRES_DB: loglens
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: loglens
      RABBITMQ_DEFAULT_PASS: loglens
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
